@url = https://8080-professional-spring0609-tq49j3up0cz.ws-us116.gitpod.io

###
POST {{url}}/pessoas
Content-Type: application/json

{
    "nome": "Kauee",
    "idade": 220
}

###
GET {{url}}/pessoas

###
GET {{url}}/pessoas/1

###
PUT {{url}}/pessoas/2
Content-Type: application/json

{
    "nome": "Registro Modificado",
    "idade": 82
}

###
DELETE {{url}}/pessoas/3